import Head from 'next/head'
import Image from 'next/image'

export default function Home({data, error}) {
  // console.log(`data`, data)
  // console.log(`error`, error)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Available campaigns</h1>
        
        {error &&<p>{error}</p>}
        {data.map((element) => <div key={element.slug}>

        <div>
          <div>
            <Image src={"https://res.cloudinary.com/dogjmmett/"+element.logo} height={120} width={120} alt="Campaign Banner" />
          </div>

          <div>
            <h1>{element.title}</h1>
            <p>{element.description}</p>
            <p>{element.created_at}</p>
          </div>
        </div>

        </div>)}
      </div>
       
    </>
  )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
}

export async function getStaticProps(){
  let data=[];
  let error = null;
  try {
    const response = await fetch(`${process.env.BASE_URL}/campaigns`)

    data = await response.json()

     
  } catch (err) {
    console.log(`err`, err)
    error= err.message ? err.message : "Something went wrong";
  }
  
  return {
    props:{
      data,
      error,
    }
  }
}